# 1. サービス定義
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080 # Nginx の待ち受けポート
      targetPort: 8080
  type: ClusterIP
---
# 2. ルート定義 (ブラウザからアクセスするためのURLを発行)
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  to:
    kind: Service
    name: frontend
  port:
    targetPort: 8080
---
# 3. デプロイメント定義
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:latest # これも後で oc set triggers するので短縮名でOK
        ports:
        - containerPort: 8080
        # 必要に応じて、APIサーバーのURLなどを環境変数で渡す
        env:
        - name: REQUEST_SERVICE_URL
          value: "http://request-service:8000"
